[package]
name = "advent_of_code_2022"
version = "0.1.0"
authors = ["Diogo Sousa <diogogsousa@gmail.com>"]
edition = "2021"

[dependencies]
itertools = "0.10.5"
scan_fmt = "0.2.6"
ndarray = "0.15.6"
num = "0.4.0"

[profile.dev]
opt-level = 3
